---
- name: Manage CML devices
  hosts: ios-all
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output

- name: CE specific config
  hosts: 192.168.255.127,192.168.255.162,192.168.255.128
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: Create Username and Password
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - username akahric privilege 15 secret cisco
          - username hamdija privilege 15 secret cisco

      register: print_output

    -  debug: var=print_output
