---
- name: Check VRF configuration and operation
  hosts: ASR
  gather_facts: false
  connection: local

  tasks:
    - name: show commands are running
      ios_command:
        commands:
          # change the name for your required vrf
          - sh run vrf aha-003055 
          - sh bgp vpnv4 unicast vrf aha-003055 summ
          - sh ip vrf int aha-003055
          - sh ip route vrf aha-003055 

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

# Commands to run:
#1) ansible-playbook ios-xe_sh_vrf_customer.yaml -u akahric -k
# !!Please change to your username and use your radius password when prompted
