---
- name: Check MPLS configuration and operation
  hosts: ASR
  gather_facts: false
  connection: local

  tasks:
    - name: show commands are running
      ios_command:
        commands:
          - sh run | s mpls
          - sh mpls ldp neighb
          - sh mpls interfaces
          - sh mpls ldp binding 

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

# Commands to run:
#1) ansible-playbook ios-xe_sh_mpls.yaml -u akahric -k
# !!Please change to your username and use your radius password when prompted
